classDiagram
    class AtomsState
    class CoreHole
    class HubbardInteractions
    class OrbitalsState
    AtomsState --> CoreHole : core_hole
    AtomsState --> HubbardInteractions : hubbard_interactions
    AtomsState --> OrbitalsState : orbitals_state
