classDiagram
    class BaseGreensFunction
    class CrystalFieldSplitting
    class ElectronicGreensFunction
    class ElectronicSelfEnergy
    class Frequency
    class HoppingMatrix
    class HybridizationFunction
    class ImaginaryTime
    class MatsubaraFrequency
    class QuasiparticleWeight
    class Time
    class WignerSeitz
    BaseGreensFunction <|-- ElectronicGreensFunction
    BaseGreensFunction <|-- ElectronicSelfEnergy
    BaseGreensFunction <|-- HybridizationFunction
    BaseGreensFunction --> Frequency : real_frequency
    BaseGreensFunction --> ImaginaryTime : imaginary_time
    BaseGreensFunction --> MatsubaraFrequency : matsubara_frequency
    BaseGreensFunction --> Time : time
    BaseGreensFunction --> WignerSeitz : wigner_seitz
