classDiagram
    class Cell
    class ChemicalFormula
    class ModelSystem
    class ParticleState
    class Symmetry
    ModelSystem --> Cell : cell
    ModelSystem --> ChemicalFormula : chemical_formula
    ModelSystem --> ModelSystem : sub_systems
    ModelSystem --> ParticleState : particle_states
    ModelSystem --> Symmetry : symmetry
