classDiagram
    class BSE
    class BaseModelMethod
    class CoreHoleSpectra
    class DFT
    class DMFT
    class ExcitedStateMethodology
    class ForceField
    class GW
    class ModelMethod
    class ModelMethodElectronic
    class NumericalSettings
    class Photon
    class Potential
    class Screening
    class Simulation
    class SlaterKoster
    class SlaterKosterBond
    class TB
    class Wannier
    class XCFunctional
    class xTB
    ExcitedStateMethodology <|-- BSE
    ModelMethodElectronic <|-- CoreHoleSpectra
    ModelMethodElectronic <|-- DFT
    ModelMethodElectronic <|-- DMFT
    ModelMethodElectronic <|-- ExcitedStateMethodology
    ModelMethod <|-- ForceField
    ExcitedStateMethodology <|-- GW
    BaseModelMethod <|-- ModelMethod
    ModelMethod <|-- ModelMethodElectronic
    BaseModelMethod <|-- Potential
    ExcitedStateMethodology <|-- Screening
    TB <|-- SlaterKoster
    ModelMethodElectronic <|-- TB
    TB <|-- Wannier
    TB <|-- xTB
    BaseModelMethod --> NumericalSettings : numerical_settings
    DFT --> XCFunctional : xc_functionals
    ForceField --> Potential : contributions
    ModelMethod --> BaseModelMethod : contributions
    Simulation --> ModelMethod : model_method
    SlaterKoster --> SlaterKosterBond : bonds
    SlaterKoster --> SlaterKosterBond : overlaps
