classDiagram
    class BSE
    class BaseModelMethod
    class CoreHoleSpectra
    class DFT
    class DMFT
    class ExcitedStateMethodology
    class GW
    class ModelMethod
    class ModelMethodElectronic
    class Photon
    class Screening
    class SlaterKoster
    class SlaterKosterBond
    class TB
    class Wannier
    class XCFunctional
    class xTB
    ExcitedStateMethodology <|-- BSE
    ModelMethodElectronic <|-- CoreHoleSpectra
    ModelMethodElectronic <|-- DFT
    ModelMethodElectronic <|-- DMFT
    ModelMethodElectronic <|-- ExcitedStateMethodology
    ExcitedStateMethodology <|-- GW
    BaseModelMethod <|-- ModelMethod
    ModelMethod <|-- ModelMethodElectronic
    ExcitedStateMethodology <|-- Screening
    TB <|-- SlaterKoster
    ModelMethodElectronic <|-- TB
    TB <|-- Wannier
    TB <|-- xTB
    DFT --> XCFunctional : xc_functionals
    ModelMethod --> BaseModelMethod : contributions
    SlaterKoster --> SlaterKosterBond : bonds
    SlaterKoster --> SlaterKosterBond : overlaps
