classDiagram
    class APWPlaneWaveBasisSet
    class AtomCenteredFunction
    class BasisSetComponent
    class ForceCalculations
    class KLinePath
    class KMesh
    class KSpace
    class Mesh
    class NumericalSettings
    class PlaneWaveBasisSet
    class SelfConsistency
    class Smearing
    PlaneWaveBasisSet <|-- APWPlaneWaveBasisSet
    NumericalSettings <|-- ForceCalculations
    Mesh <|-- KMesh
    NumericalSettings <|-- KSpace
    BasisSetComponent <|-- PlaneWaveBasisSet
    KMesh <|-- PlaneWaveBasisSet
    NumericalSettings <|-- SelfConsistency
    NumericalSettings <|-- Smearing
    KSpace --> KLinePath : k_line_path
    KSpace --> KMesh : k_mesh
