classDiagram
    class AbsorptionSpectrum
    class BaseElectronicEigenvalues
    class BaseEnergy
    class BaseForce
    class BaseGreensFunction
    class ChemicalPotential
    class CrystalFieldSplitting
    class ElectronicBandGap
    class ElectronicBandStructure
    class ElectronicDensityOfStates
    class ElectronicEigenvalues
    class ElectronicGreensFunction
    class ElectronicSelfEnergy
    class Entropy
    class FermiSurface
    class HeatCapacity
    class Hessian
    class HoppingMatrix
    class HybridizationFunction
    class KineticEnergy
    class MassDensity
    class Occupancy
    class Outputs
    class Permittivity
    class PhysicalProperty
    class PotentialEnergy
    class Pressure
    class QuasiparticleWeight
    class SCFOutputs
    class Simulation
    class SpectralProfile
    class Temperature
    class Time
    class TotalEnergy
    class TotalForce
    class Volume
    class WorkflowOutputs
    class XASSpectrum
    SpectralProfile <|-- AbsorptionSpectrum
    PhysicalProperty <|-- BaseElectronicEigenvalues
    PhysicalProperty <|-- BaseEnergy
    PhysicalProperty <|-- BaseForce
    PhysicalProperty <|-- BaseGreensFunction
    BaseEnergy <|-- ChemicalPotential
    PhysicalProperty <|-- CrystalFieldSplitting
    PhysicalProperty <|-- ElectronicBandGap
    ElectronicEigenvalues <|-- ElectronicBandStructure
    BaseElectronicEigenvalues <|-- ElectronicEigenvalues
    BaseGreensFunction <|-- ElectronicGreensFunction
    BaseGreensFunction <|-- ElectronicSelfEnergy
    PhysicalProperty <|-- Entropy
    PhysicalProperty <|-- FermiSurface
    PhysicalProperty <|-- HeatCapacity
    PhysicalProperty <|-- Hessian
    PhysicalProperty <|-- HoppingMatrix
    BaseGreensFunction <|-- HybridizationFunction
    BaseEnergy <|-- KineticEnergy
    PhysicalProperty <|-- MassDensity
    PhysicalProperty <|-- Occupancy
    Time <|-- Outputs
    PhysicalProperty <|-- Permittivity
    BaseEnergy <|-- PotentialEnergy
    PhysicalProperty <|-- Pressure
    PhysicalProperty <|-- QuasiparticleWeight
    Outputs <|-- SCFOutputs
    PhysicalProperty <|-- SpectralProfile
    PhysicalProperty <|-- Temperature
    BaseEnergy <|-- TotalEnergy
    BaseForce <|-- TotalForce
    PhysicalProperty <|-- Volume
    Outputs <|-- WorkflowOutputs
    AbsorptionSpectrum <|-- XASSpectrum
    BaseGreensFunction --> Time : time
    ElectronicEigenvalues --> BaseElectronicEigenvalues : value_contributions
    Outputs --> AbsorptionSpectrum : absorption_spectra
    Outputs --> ChemicalPotential : chemical_potentials
    Outputs --> CrystalFieldSplitting : crystal_field_splittings
    Outputs --> ElectronicBandGap : electronic_band_gaps
    Outputs --> ElectronicBandStructure : electronic_band_structures
    Outputs --> ElectronicDensityOfStates : electronic_dos
    Outputs --> ElectronicEigenvalues : electronic_eigenvalues
    Outputs --> ElectronicGreensFunction : electronic_greens_functions
    Outputs --> ElectronicSelfEnergy : electronic_self_energies
    Outputs --> FermiSurface : fermi_surfaces
    Outputs --> HoppingMatrix : hopping_matrices
    Outputs --> HybridizationFunction : hybridization_functions
    Outputs --> KineticEnergy : kinetic_energies
    Outputs --> Occupancy : occupancies
    Outputs --> Permittivity : permittivities
    Outputs --> PotentialEnergy : potential_energies
    Outputs --> QuasiparticleWeight : quasiparticle_weights
    Outputs --> Temperature : temperatures
    Outputs --> TotalEnergy : total_energies
    Outputs --> TotalForce : total_forces
    Outputs --> XASSpectrum : xas_spectra
    PhysicalProperty --> PhysicalProperty : contributions
    SCFOutputs --> Outputs : scf_steps
    Simulation --> Outputs : outputs
    TotalEnergy --> BaseEnergy : contributions
    TotalForce --> BaseForce : contributions
    XASSpectrum --> AbsorptionSpectrum : exafs_spectrum
    XASSpectrum --> AbsorptionSpectrum : xanes_spectrum
