classDiagram
    class Outputs
    class PhysicalProperty
    class SCFOutputs
    Outputs <|-- SCFOutputs
    PhysicalProperty --> PhysicalProperty : contributions
    SCFOutputs --> Outputs : scf_steps
