classDiagram
    class AtomsState
    class CGBeadState
    class CoreHole
    class HubbardInteractions
    class OrbitalsState
    class ParticleState
    ParticleState <|-- AtomsState
    ParticleState <|-- CGBeadState
    AtomsState --> CoreHole : core_hole
    AtomsState --> HubbardInteractions : hubbard_interactions
    AtomsState --> OrbitalsState : orbitals_state
