classDiagram
    class BaseSimulation
    class ModelMethod
    class ModelSystem
    class Outputs
    class Program
    class Simulation
    class Time
    Time <|-- BaseSimulation
    Time <|-- Outputs
    BaseSimulation <|-- Simulation
    BaseSimulation --> Program : program
    ModelSystem --> ModelSystem : sub_systems
    Simulation --> ModelMethod : model_method
    Simulation --> ModelSystem : model_system
    Simulation --> Outputs : outputs
