classDiagram
    class BaseSimulation
    class ModelMethod
    class ModelSystem
    class Outputs
    class Program
    class Simulation
    BaseSimulation <|-- Simulation
    BaseSimulation --> Program : program
    Simulation --> ModelMethod : model_method
    Simulation --> ModelSystem : model_system
    Simulation --> Outputs : outputs
