classDiagram
    class BaseEnergy
    class BaseForce
    class ChemicalPotential
    class Enthalpy
    class Entropy
    class GibbsFreeEnergy
    class Heat
    class HeatCapacity
    class HelmholtzFreeEnergy
    class Hessian
    class InternalEnergy
    class KineticEnergy
    class MassDensity
    class Outputs
    class PhysicalProperty
    class PotentialEnergy
    class Pressure
    class Temperature
    class TotalEnergy
    class TotalForce
    class Variables
    class VirialTensor
    class Volume
    class Work
    PhysicalProperty <|-- BaseEnergy
    PhysicalProperty <|-- BaseForce
    BaseEnergy <|-- ChemicalPotential
    BaseEnergy <|-- Enthalpy
    PhysicalProperty <|-- Entropy
    BaseEnergy <|-- GibbsFreeEnergy
    BaseEnergy <|-- Heat
    PhysicalProperty <|-- HeatCapacity
    BaseEnergy <|-- HelmholtzFreeEnergy
    PhysicalProperty <|-- Hessian
    BaseEnergy <|-- InternalEnergy
    BaseEnergy <|-- KineticEnergy
    PhysicalProperty <|-- MassDensity
    BaseEnergy <|-- PotentialEnergy
    PhysicalProperty <|-- Pressure
    PhysicalProperty <|-- Temperature
    Variables <|-- Temperature
    BaseEnergy <|-- TotalEnergy
    BaseForce <|-- TotalForce
    BaseEnergy <|-- VirialTensor
    PhysicalProperty <|-- Volume
    BaseEnergy <|-- Work
    Outputs --> ChemicalPotential : chemical_potentials
    Outputs --> KineticEnergy : kinetic_energies
    Outputs --> PotentialEnergy : potential_energies
    Outputs --> Temperature : temperatures
    Outputs --> TotalEnergy : total_energies
    Outputs --> TotalForce : total_forces
    PhysicalProperty --> PhysicalProperty : contributions
    TotalEnergy --> BaseEnergy : contributions
    TotalForce --> BaseForce : contributions
